### ISSUE TITLE
Python 3.6 support?

### ISSUE THREAD

**Issue by KinglittleQ** [facebookresearch/AugLy#101]
## 🚀 Feature

Support Python 3.6

## Motivation

Python 3.6 is a widely used Python version. Could you add support to it? Or is there any problem to support Python 3.6?

**Comment by zpapakipos** [comment]
Hi @KinglittleQ this was actually just a typo in the `setup.py` file, python 3.6 does work with AugLy :) Fixing it now in https://github.com/facebookresearch/AugLy/pull/117!
