### ISSUE TITLE
Intensity of zero instead a weighted value

### ISSUE THREAD

**Issue by BrandonHT** [facebookresearch/AugLy#102]
## 🐛 Bug

Using the color_jitter function for images, if user does not specify a different value than 1.0 to factor parameters, the intensity function will return 0.0, while might return a weighted intensity of the actions did. 
The mult_factor_intensity_helper function specifies that if a factor value is 1 the intensity should be 0.0, maybe could be changed to another helper function to create the weighted intensity. 

## To Reproduce

1. Use an image and the function color_jitter
2. Give a value to one or two factor parameters

## Expected behavior

The intensity value returned in the metadata might be a weighted intensity. 

## Environment

 - AugLy Version: 0.1.5
 - OS (e.g., Linux): Jupyter notebook
 - How you installed AugLy (`pip install augly`, clone & `pip install -e AugLy`): clone

# Example
aug_image = imaugs.color_jitter(image_path, brightness_factor=0.5, contrast_factor=1.3, saturation_factor=1.0, output_path=output_path, metadata=meta_color_jitter)

and metadata contains the following info:

'name':	'color_jitter'
'src_width':	'640'
'src_height':	'426'
'dst_width':	'640'
'dst_height':	'426'
'output_path':	'/content/images/output.png'
'brightness_factor':	'0.5'
'contrast_factor':	'1.3'
'saturation_factor':	'1.0'
'intensity':	'0.0'

**Comment by zpapakipos** [comment]
Hi @BrandonHT thanks for pointing this out! I'm working on a fix now, will link to this issue from the PR :)
