### ISSUE TITLE
Example in AugLy_image.ipynb for bounding boxes doesn't work

### ISSUE THREAD

**Issue by Adib234** [facebookresearch/AugLy#122]
## To Reproduce

1. Go to AugLy_image.ipynb and try running the example with the bounded boxes

This is the snippet of code I'm running which is from `AugLy_image.ipynb`
```python3
"""
You can also pass in bounding boxes, which will be transformed along with the 
image & included in the metadata (note: you must provide metadata to get
the transformed bboxes
"""
meta = []
display(
    imaugs.rotate(
        input_img,
        degrees=15,
        metadata=meta,
        bboxes=[(20, 6, 500, 600)],
        bbox_format="pascal_voc",
    )
)
meta
```
which gives me the following error message

```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
/var/folders/tb/pj8zr8qn57q8t6cldym25fgw0000gn/T/ipykernel_92443/4056688084.py in <module>
      6 meta = []
      7 display(
----> 8     imaugs.rotate(
      9         input_img,
     10         degrees=15,

TypeError: rotate() got an unexpected keyword argument 'bboxes'
```

I have to remove arguments `bboxes` and `bboxes_format` for this to run without any error messages, which finally gives me this
![image](https://user-images.githubusercontent.com/30782825/134229284-6907cf99-6c15-4638-bdde-09671e055b5b.png)

## Expected behavior

I expected this to work, or run without any error messages.

## Environment

 - AugLy Version (e.g., 0.1.2): 0.1.7
 - OS (e.g., Linux): MacOS
 - How you installed AugLy (`pip install augly`, clone & `pip install -e AugLy`): `pip install augly`
 - Python version: 3.9.6
 - Other relevant packages (Tensorflow, etc): n/a

**Comment by zpapakipos** [comment]
Hi @Adib234 thanks for the catch! This is because I hadn't updated the package on pypi yet; now I have, so the notebook should work just fine :)
