### ISSUE TITLE
Python 3.6.2 module 'augly' has no attribute 'image'.

### ISSUE THREAD

**Issue by iseessel** [facebookresearch/AugLy#137]
## To Reproduce

```
conda create -n augly_test python=3.6.2
conda activate augly_test
pip install augly
python -c "import augly.image"

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/iseessel/anaconda3/envs/augly_test/lib/python3.6/site-packages/augly/image/__init__.py", line 4, in <module>
    from augly.image.composition import Compose, OneOf
  File "/Users/iseessel/anaconda3/envs/augly_test/lib/python3.6/site-packages/augly/image/composition.py", line 7, in <module>
    from augly.image.transforms import BaseTransform
  File "/Users/iseessel/anaconda3/envs/augly_test/lib/python3.6/site-packages/augly/image/transforms.py", line 8, in <module>
    import augly.image.functional as F
  File "/Users/iseessel/anaconda3/envs/augly_test/lib/python3.6/site-packages/augly/image/functional.py", line 11, in <module>
    import augly.image.utils as imutils
  File "/Users/iseessel/anaconda3/envs/augly_test/lib/python3.6/site-packages/augly/image/utils/__init__.py", line 4, in <module>
    from augly.image.utils.metadata import get_func_kwargs, get_metadata
  File "/Users/iseessel/anaconda3/envs/augly_test/lib/python3.6/site-packages/augly/image/utils/metadata.py", line 7, in <module>
    import augly.image.intensity as imintensity
  File "/Users/iseessel/anaconda3/envs/augly_test/lib/python3.6/site-packages/augly/image/intensity.py", line 6, in <module>
    import augly.image.utils as imutils
AttributeError: module 'augly' has no attribute 'image'

conda install -c conda-forge python-magic
 $ python -c "import augly.image"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/iseessel/anaconda3/envs/augly_test/lib/python3.6/site-packages/augly/image/__init__.py", line 4, in <module>
    from augly.image.composition import Compose, OneOf
  File "/Users/iseessel/anaconda3/envs/augly_test/lib/python3.6/site-packages/augly/image/composition.py", line 7, in <module>
    from augly.image.transforms import BaseTransform
  File "/Users/iseessel/anaconda3/envs/augly_test/lib/python3.6/site-packages/augly/image/transforms.py", line 8, in <module>
    import augly.image.functional as F
  File "/Users/iseessel/anaconda3/envs/augly_test/lib/python3.6/site-packages/augly/image/functional.py", line 11, in <module>
    import augly.image.utils as imutils
  File "/Users/iseessel/anaconda3/envs/augly_test/lib/python3.6/site-packages/augly/image/utils/__init__.py", line 4, in <module>
    from augly.image.utils.metadata import get_func_kwargs, get_metadata
  File "/Users/iseessel/anaconda3/envs/augly_test/lib/python3.6/site-packages/augly/image/utils/metadata.py", line 7, in <module>
    import augly.image.intensity as imintensity
  File "/Users/iseessel/anaconda3/envs/augly_test/lib/python3.6/site-packages/augly/image/intensity.py", line 6, in <module>
    import augly.image.utils as imutils
AttributeError: module 'augly' has no attribute 'image'
```

List of packages: 

```
 $ conda list
# packages in environment at /Users/iseessel/anaconda3/envs/augly_test:
#
# Name                    Version                   Build  Channel
augly                     0.1.9                    pypi_0    pypi
ca-certificates           2021.5.30            h033912b_0    conda-forge
certifi                   2021.5.30        py36h79c6626_0    conda-forge
dataclasses               0.8                      pypi_0    pypi
iopath                    0.1.9                    pypi_0    pypi
libcxx                    12.0.0               h2f01273_0
libedit                   3.1.20210714         h9ed2024_0
libffi                    3.2.1             h0a44026_1007
libmagic                  5.39                 haaf19a9_0    conda-forge
ncurses                   6.2                  h0a44026_1
nlpaug                    1.1.3                    pypi_0    pypi
numpy                     1.19.5                   pypi_0    pypi
openssl                   1.0.2u               h0b31af3_0    conda-forge
pillow                    8.3.2                    pypi_0    pypi
pip                       21.2.2           py36hecd8cb5_0
portalocker               2.3.2                    pypi_0    pypi
python                    3.6.2               hd04bb42_19
python-magic              0.4.24           py36h79c6626_0    conda-forge
python_abi                3.6                     2_cp36m    conda-forge
readline                  7.0                  h1de35cc_5
regex                     2021.9.30                pypi_0    pypi
setuptools                58.0.4           py36hecd8cb5_0
sqlite                    3.33.0               hffcf06c_0
tk                        8.6.11               h7bc2e8c_0
tqdm                      4.62.3                   pypi_0    pypi
wheel                     0.37.0             pyhd3eb1b0_1
xz                        5.2.5                h1de35cc_0
zlib                      1.2.11               h1de35cc_3
```

## Expected behavior

Import Fails. Note: I've tried the same on python3.8.

## Environment

 - AugLy Version (e.g., 0.1.2): 0.1.9 
 - OS (e.g., Linux): macOS Big Sur (11.6)
 - How you installed AugLy (`pip install augly`, clone & `pip install -e AugLy`): See above.
 - Python version: 3.6.2

**Comment by Tristacheng** [comment]
> ## 🐛 Bug
> ## To Reproduce
> Steps to reproduce the behavior:
> 
> ```
> conda create -n augly_test python=3.6.2
> conda activate augly_test
> pip install augly
> python -c "import augly.image"
> 
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/Users/iseessel/anaconda3/envs/augly_test/lib/python3.6/site-packages/augly/image/__init__.py", line 4, in <module>
>     from augly.image.composition import Compose, OneOf
>   File "/Users/iseessel/anaconda3/envs/augly_test/lib/python3.6/site-packages/augly/image/composition.py", line 7, in <module>
>     from augly.image.transforms import BaseTransform
>   File "/Users/iseessel/anaconda3/envs/augly_test/lib/python3.6/site-packages/augly/image/transforms.py", line 8, in <module>
>     import augly.image.functional as F
>   File "/Users/iseessel/anaconda3/envs/augly_test/lib/python3.6/site-packages/augly/image/functional.py", line 11, in <module>
>     import augly.image.utils as imutils
>   File "/Users/iseessel/anaconda3/envs/augly_test/lib/python3.6/site-packages/augly/image/utils/__init__.py", line 4, in <module>
>     from augly.image.utils.metadata import get_func_kwargs, get_metadata
>   File "/Users/iseessel/anaconda3/envs/augly_test/lib/python3.6/site-packages/augly/image/utils/metadata.py", line 7, in <module>
>     import augly.image.intensity as imintensity
>   File "/Users/iseessel/anaconda3/envs/augly_test/lib/python3.6/site-packages/augly/image/intensity.py", line 6, in <module>
>     import augly.image.utils as imutils
> AttributeError: module 'augly' has no attribute 'image'
> 
> conda install -c conda-forge python-magic
>  $ python -c "import augly.image"
> Traceback (most recent call last):
>   File "<string>", line 1, in <module>
>   File "/Users/iseessel/anaconda3/envs/augly_test/lib/python3.6/site-packages/augly/image/__init__.py", line 4, in <module>
>     from augly.image.composition import Compose, OneOf
>   File "/Users/iseessel/anaconda3/envs/augly_test/lib/python3.6/site-packages/augly/image/composition.py", line 7, in <module>
>     from augly.image.transforms import BaseTransform
>   File "/Users/iseessel/anaconda3/envs/augly_test/lib/python3.6/site-packages/augly/image/transforms.py", line 8, in <module>
>     import augly.image.functional as F
>   File "/Users/iseessel/anaconda3/envs/augly_test/lib/python3.6/site-packages/augly/image/functional.py", line 11, in <module>
>     import augly.image.utils as imutils
>   File "/Users/iseessel/anaconda3/envs/augly_test/lib/python3.6/site-packages/augly/image/utils/__init__.py", line 4, in <module>
>     from augly.image.utils.metadata import get_func_kwargs, get_metadata
>   File "/Users/iseessel/anaconda3/envs/augly_test/lib/python3.6/site-packages/augly/image/utils/metadata.py", line 7, in <module>
>     import augly.image.intensity as imintensity
>   File "/Users/iseessel/anaconda3/envs/augly_test/lib/python3.6/site-packages/augly/image/intensity.py", line 6, in <module>
>     import augly.image.utils as imutils
> AttributeError: module 'augly' has no attribute 'image'
> ```
> 
> List of packages:
> 
> ```
>  $ conda list
> # packages in environment at /Users/iseessel/anaconda3/envs/augly_test:
> #
> # Name                    Version                   Build  Channel
> augly                     0.1.9                    pypi_0    pypi
> ca-certificates           2021.5.30            h033912b_0    conda-forge
> certifi                   2021.5.30        py36h79c6626_0    conda-forge
> dataclasses               0.8                      pypi_0    pypi
> iopath                    0.1.9                    pypi_0    pypi
> libcxx                    12.0.0               h2f01273_0
> libedit                   3.1.20210714         h9ed2024_0
> libffi                    3.2.1             h0a44026_1007
> libmagic                  5.39                 haaf19a9_0    conda-forge
> ncurses                   6.2                  h0a44026_1
> nlpaug                    1.1.3                    pypi_0    pypi
> numpy                     1.19.5                   pypi_0    pypi
> openssl                   1.0.2u               h0b31af3_0    conda-forge
> pillow                    8.3.2                    pypi_0    pypi
> pip                       21.2.2           py36hecd8cb5_0
> portalocker               2.3.2                    pypi_0    pypi
> python                    3.6.2               hd04bb42_19
> python-magic              0.4.24           py36h79c6626_0    conda-forge
> python_abi                3.6                     2_cp36m    conda-forge
> readline                  7.0                  h1de35cc_5
> regex                     2021.9.30                pypi_0    pypi
> setuptools                58.0.4           py36hecd8cb5_0
> sqlite                    3.33.0               hffcf06c_0
> tk                        8.6.11               h7bc2e8c_0
> tqdm                      4.62.3                   pypi_0    pypi
> wheel                     0.37.0             pyhd3eb1b0_1
> xz                        5.2.5                h1de35cc_0
> zlib                      1.2.11               h1de35cc_3
> ```
> 
> ## Expected behavior
> Import Fails. Note: I've tried the same on python3.8.
> 
> ## Environment
> * AugLy Version (e.g., 0.1.2): 0.1.9
> * OS (e.g., Linux): macOS Big Sur (11.6)
> * How you installed AugLy (`pip install augly`, clone & `pip install -e AugLy`): See above.
> * Python version: 3.6.2

Have you solved it? Python 3.6.13 has the same problem

**Comment by cailun01** [comment]
Hi @zpapakipos @Tristacheng , change the way of import module can solve this problem. 
At `augly/image/intensity.py`, change 
```python
import augly.image.utils as imutils
```
to
```python
from augly.image import utils as imutils
```

At `augly/image/utils/metadata.py`, change
```python
import augly.image.intensity as imintensity
import augly.image.utils.bboxes as imbboxes
```
to
```python
from augly.image import intensity as imintensity
from augly.image.utils import bboxes as iminteimbboxesnsity
```

At `augly/image/utils/bboxes.py`, change
```python
import augly.image.utils as imutils
```
to
```python
from augly.image import utils as imutils
```

At `augly/image/functional.py`, change
```python
import augly.image.utils as imutils
import augly.utils as utils
```
to
```python
from augly.image import utils as imutils
from augly import utils
```

At `augly/image/transforms.py`, change
```python
import augly.image.functional as F
import augly.utils as utils
```
to
```python
from augly.image import functional as F
from augly import utils
```

**Comment by zpapakipos** [comment]
Sorry for the delay on this issue -- it was just reported again in https://github.com/facebookresearch/AugLy/issues/159, so I'll prioritize fixing this soon so that AugLy is usable with python 3.6.

**Comment by zpapakipos** [comment]
Update: I landed https://github.com/facebookresearch/AugLy/pull/160 which modified the imports to be python 3.6-compatible. On my side I verified that I have no issue running AugLy in a conda env using python 3.6. Please reopen this issue if anyone sees this issue again!

**Comment by iseessel** [comment]
Thank you @zpapakipos!
