### ISSUE TITLE
[BUG] Return type problem in text transformation functions

### ISSUE THREAD

**Issue by Antoine-Prieur** [facebookresearch/AugLy#189]
## 🐛 Bug

Hello, there seems to be a type issue in the text transformations functions in the `augly/text/functional.py` file. Indeed, these functions can take a string or a list of strings as inputs, and return a new string or list of strings based on the input type.

```
textaugs.simulate_typos(["hello"])  # returns a list of strings
textaugs.simulate_typos("hello")  # returns a string
```

However, all the functions are defined as : 

```
def change_case(
    texts: Union[str, List[str]],
    ...
) -> List[str]:
    pass
```

## Expected behavior

Is it possible to change the types of the functions as something like this to solve this issue : 

```
from typing import TypeVar

T = TypeVar("T", str, List[str])
def change_case(
    texts: T,
    ...
) -> T:
    pass
```

## Environment

 - AugLy Version: 0.2.1
 - Python version: 3.8.5

**Comment by zpapakipos** [comment]
Hi @Antoine-Prieur, thanks for pointing this out! You're right that the text augmentations all can take in `Union[str, List[str]]` and then output the same, so we should change the type signatures to match. I'll start a PR to fix this :)
