### ISSUE TITLE
`pickle` is a security issue and should not be used

### ISSUE THREAD

**Issue by KOLANICH** [facebookresearch/AugLy#192]
## 🚀 Feature
Eliminate pickle.

## Motivation

`pickle` can be used to create covert backdoors.

## Pitch

1. Remove all the pickle files from the repo
2. Remove all the `pickle` imports from the source code

## Alternatives

Using packages providing means for safe fully-controlled unpickling. Not very useful, since it will be no different to manual deserialization.

**Comment by zpapakipos** [comment]
Hello @KOLANICH, thank you these issues and for your interest in helping improve AugLy! I'll respond to your issues one by one.

For this one, we are aware that Pickle can be a security risk, however we are pretty confident that the way we are using it (to read static pkl files which come from a bundle of fonts) does not pose a significant security risk. However, if you would like to make this change we are open to it and happy to review a PR.

**Comment by zpapakipos** [comment]
Closing this for now. @KOLANICH please let me know if you'd like to work on this or disagree with my comment above and I'll reopen it.

**Comment by KOLANICH** [comment]
IDK currently if I gonna work on this. Depends on a lot of factors. One of which is that currently IDK what's inside these pickle files (I haven't deserialized them, when installing the package to my machine I have just removed them all, so for me text-based image augmentations are broken (but I don't need them anyway) but t least no untrusted code is executed).
