### ISSUE TITLE
Split the library into multiple ones

### ISSUE THREAD

**Issue by KOLANICH** [facebookresearch/AugLy#193]
## Motivation

>Each modality’s augmentations are contained within its own sub-library. 

## Pitch

Each sub-library should be a separate python package.

## Alternatives

No.

**Comment by zpapakipos** [comment]
Hi @KOLANICH, this is indeed something we have considered in the past as AugLy will no doubt continue to grow and gain functionality, and we would like for users to have the option to download individual modalities. I will add this to our backlog of tasks and will make this change when we have time. Alternatively if you would like to create a PR making this change, I'm happy to review it.

**Comment by KOLANICH** [comment]
Thanks.
