### ISSUE TITLE
The script for generation of the pickle files for fonts seems to be not provided.

### ISSUE THREAD

**Issue by KOLANICH** [facebookresearch/AugLy#194]
## 🐛 Bug

The script for generation of the pickle files seems to be not provided.

## To Reproduce

```bash
rm -rf ./augly/assets/fonts/*.pkl
rm -rf ./examples
rm -rf ./augly/assets/tests
grep -Rl pkl
```

## Expected behavior

Some file with the code generating those pickles should be found.

## Environment

 - AugLy Version (e.g., 0.1.2): 1e414df2381d77b690ffb99f8fda4bc839bc88fb
 - OS (e.g., Linux): anything with `grep`
 - How you installed AugLy (`pip install augly`, clone & `pip install -e AugLy`): from git
 - Python version: 3.9

**Comment by zpapakipos** [comment]
Hi @KOLANICH, I'm not exactly sure what you mean by this. The pkl files we have came bundled with the other font files. If you have an example or idea of how such a script would look, feel free to send it over so we can take a look.

**Comment by KOLANICH** [comment]
The pickle files came bundled, but pickles are code execution, and I don't want to execute any code I don't trust. I surely don't trust the code I don't know. I think these precomputed info about fonts should be generated in runtime on demand for any font user specifies, and not come precomputed in a form of pickle files with unknown code inside.

So I wonder what's inside of these pickle files and how are they generated and if they can be replaced with some other serialization methid that is more trustworthy.
