### ISSUE TITLE
Augly should use system-installed fonts instead of bundled ones

### ISSUE THREAD

**Issue by KOLANICH** [facebookresearch/AugLy#195]
## Motivation

1. Bundled fonts cause the package be unnecessarily bloated.
2. Minor differences between fonts versions are not signifcant enough to spoil ML pipelines to justify bundling. Ones who want deterministic environment can use Docker and other containers or provide a path to a dir with their own fonts.
3. Using system-installed fonts can bring greater variety into augmentations.

## Pitch
1. eliminate bundled fonts
2. implement a mechanism using system-installed fonts and use it by default
3. Implement a function giving a fingerprint of the environment in a form of a hash of font-based augmentations to an empty image.
4. Implement a mechanism for users to specify own fonts to be used.

## Alternatives

None.

**Comment by zpapakipos** [comment]
Hi @KOLANICH, I definitely see your point here that including so many assets with AugLy bloats the package. However, we also know that many users use and rely on the included fonts, so we prefer to err on the side of not changing the package in this way for now. I'll close the issue for now, and if more users agree that this would be preferable then we can revisit later on.
