### ISSUE TITLE
Move test data out of `augly` dir

### ISSUE THREAD

**Issue by KOLANICH** [facebookresearch/AugLy#196]
## Motivation

They unneededly bloat the wheel.

## Pitch

```bash
git mv augly/assets/tests test_data
```

## Alternatives

No.

**Comment by zpapakipos** [comment]
Hi @KOLANICH, I do see your point here and agree that this would be a fine solution seeing that we don't expect users to run the tests unless they have cloned the repo, in which case they will already have the test data if outside the main `augly` dir, so we don't need to include it in the wheel. I will add this to our backlog of tasks and get to it when we have time.

**Comment by KOLANICH** [comment]
Thanks.
