### ISSUE TITLE
Problem with open font file

### ISSUE THREAD

**Issue by amlarraz** [facebookresearch/AugLy#25]
Hi! I'm testing your library (concretely the text part) with spanish language following [this examplea](https://github.com/facebookresearch/AugLy/blob/main/examples/AugLy_text.ipynb) . In this process the library throws me an error when it tries to open the fonts file because an encoding problem (It can't understand some characters). 

I've changed [this line](https://github.com/facebookresearch/AugLy/blob/bf7f25f6333703e4ce663dbce2e401b433715af0/augly/text/augmenters/fun_fonts.py#L65) by: `with open(local_fonts_path, encoding='utf-8') as text_file:` and it works.

**Comment by jbitton** [comment]
Nice catch @amlarraz and thank you for opening a PR! It was just merged :) Gonna close this issue for now, feel free to reopen it if you run into any more problems :)
