### ISSUE TITLE
ReplaceSynonyms   functionality

### ISSUE THREAD

**Issue by karthikcs** [facebookresearch/AugLy#27]
I see `ReplaceSynonyms` in `text/__init__.py`, but I don't see that is implemented yet. Are we expecting this functionality any soon?

**Comment by jbitton** [comment]
Hi @karthikcs! Nice catch :) We initially implemented a `ReplaceSynonyms` augmenter, but deemed that it wasn't high-quality enough for open sourcing (for now). It's definitely in our backlog though to revamp that function and OS it!

**Comment by jbitton** [comment]
(gonna close this issue for now, feel free to reopen it if you have any more questions!)
