### ISSUE TITLE
I want transfer telegram members one CHANAl to an other chanel please tell me how to add ??

### ISSUE THREAD

**Issue by ayaz175** [facebookresearch/AugLy#31]
I want transfer telegram members one CHANAl to an other chanel

**Comment by ayaz175** [comment]
I want transfer telegram members one CHANAl to an other chanel

**Comment by jbitton** [comment]
Since this doesn't seem to be relevant to our library, I'm gonna close this issue. Feel free to reopen and update the description if you need help with AugLy
