### ISSUE TITLE
Since this doesn't seem to be relevant to our library, I'm gonna close this issue. Feel free to reopen and update the description if you need help with AugLy

### ISSUE THREAD

**Issue by georgiy123** [facebookresearch/AugLy#37]
Since this doesn't seem to be relevant to our library, I'm gonna close this issue. Feel free to reopen and update the description if you need help with AugLy

_Originally posted by @zpapakipos in https://github.com/facebookresearch/AugLy/issues/35#issuecomment-864524025_

**Comment by jbitton** [comment]
Hi I'm not sure what you're asking asking for. When creating an issue, please provide details as to what exact issues you're facing. I'm gonna close this for now. If you're having an actual issue, please update your description and reopen the issue.
