### ISSUE TITLE
Instagram Filters

### ISSUE THREAD

**Issue by ryanjay0** [facebookresearch/AugLy#42]
Thank you so much for this package. It has some really great augmentations.

`aug_image = imaugs.apply_ig_filter(image_path, filter_name="clarendon")
`

In your image readme it mentions the above function but i don't see it provided in the source. Do you plan on releasing this part of the code?

**Comment by Md-Ridoy** [comment]
Yes ji

**Comment by jbitton** [comment]
Hi @ryanjay0! Nice catch -- we should definitely get rid of that from the README while the function is not open sourced (cc: @zpapakipos).

Ideally, we'd love to release this function, but we're currently not sure if we're able to yet (from a legality sense). It's definitely in our backlog to OS some kind of filter augmentation at the very least!

**Comment by zpapakipos** [comment]
Thank you @ryanjay0 for the feedback that this feature would be appreciated, we will do what we can to make sure we can open source it ASAP! :) For now, I removed the reference from the README & will close this issue to avoid confusion.
