### ISSUE TITLE
New feature: bounding boxes augmentation for images

### ISSUE THREAD

**Issue by dgallitelli** [facebookresearch/AugLy#58]
## 🚀 Feature

Bounding boxes augmentation for images

## Motivation

While AugLy makes it very easy to do data augmentation, it's still complicated to do bounding box augmentation that matches the image augmentation.

## Pitch

Being able to do data augmentation is a very nice feature to improve ML models. However, it's also necessary to be able to obtain an "augmented bounding box" that's aligned with the augmentation done on the image.

## Alternatives

Build your own bounding box augmentation following [this tutorial](https://albumentations.ai/docs/getting_started/bounding_boxes_augmentation/), but too cumbersome.
Search another library that does this automatically.

## Additional context

![image](https://user-images.githubusercontent.com/9881522/123240794-e84c2800-d4e0-11eb-93d4-7a39fda7c57f.png)

**Comment by zpapakipos** [comment]
Hi @dgallitelli, thanks for this feature request! This is on our list of features we would like to add to AugLy soon, and it's good to know that you (& others, I'm sure) would find it useful. We will move this feature to a higher priority (particularly if others chime in here or like your comment to show a high level of interest).

**Comment by kylelindgren** [comment]
Chiming in to say this would also be immensely beneficial for my group.

**Comment by Ant-Bru** [comment]
I think that also applying augmentation only inside bounding boxes would be helpful.
For example, taking the image in the first message and vertically flipping the dog bounding box would produce:

![aug_flip](https://user-images.githubusercontent.com/31627276/123546400-a5968400-d75c-11eb-8be9-09b0b966eca3.png)

**Comment by zpapakipos** [comment]
Update on this! The ability to pass in bounding boxes & see how they are transformed has been added in https://github.com/facebookresearch/AugLy/pull/120 :) I will close this issue now since that was the primary request here, but I also created a new issue (https://github.com/facebookresearch/AugLy/issues/131) for the separate request of being able to apply augmentations within a bounding box.
