### ISSUE TITLE
Group dependencies as setup.py extras

### ISSUE THREAD

**Issue by alexsounder** [facebookresearch/AugLy#65]
## 🚀 Feature
Grouping library dependencies in setup.py by modality.

## Motivation
If we are going to apply augmentations on just one modality, we shouldn't install all library dependencies needed to augment other modalities.

## Pitch
Use [extras_require](https://setuptools.readthedocs.io/en/latest/userguide/dependency_management.html#optional-dependencies) in setup.py to specify software dependencies that are required for each modality. For example, installing audio only dependencies with `augly[audio]`. Have an `[all]` option that installs all dependencies.

**Comment by zpapakipos** [comment]
Hi @alexsounder, thank you for this suggestion! :) We had started looking into a way to do something like this to lighten the base dependencies for people using just one module, but we didn't know about this way to do it. We'll add this to the TODO list & do it ASAP.
