### ISSUE TITLE
ERROR: Package 'augly' requires a different Python: 3.6.10 not in '>=3.7'

### ISSUE THREAD

**Issue by Usernamezhx** [facebookresearch/AugLy#74]
I git clone the project. and then try to install by command:pip install -r .

**Comment by Usernamezhx** [comment]
solved by : **conda create -n augly && conda activate augly && conda install pip**

**Comment by crek1423** [comment]
https://user-images.githubusercontent.com/56601466/122749873-7b038180-d2ab-11eb-8ef8-3c6023ef87f3.jpg
