### ISSUE TITLE
InsertEmojis appears in __init__, but nowhere else

### ISSUE THREAD

**Issue by Darktex** [facebookresearch/AugLy#76]
## 🐛 Bug

The init file for text augs mentions an _InsertEmoji_ transform (see [here](https://github.com/facebookresearch/AugLy/blob/main/augly/text/__init__.py#L49)) but that transform is nowhere to be seen in the repo (at least that I could find...)

## To Reproduce

1. Check mention of that line
2. No implementation to be found
3. :(

## Expected behavior

Either fix that line, or better yet if there is an InsertEmoji transform I think folks may find it useful!

**Comment by jbitton** [comment]
Hi @Darktex! Nice catch. We have a version of `insert_emoji` internally, but honestly, the quality of it isn't good enough for open sourcing in my opinion. It's also not super flexible in terms of language. 

I'll remove it from `__init__.py` for now, but know it's in our backlog to improve on it and open source!
