### ISSUE TITLE
Function/Class is not available.

### ISSUE THREAD

**Issue by WangWenhao0716** [facebookresearch/AugLy#78]
```
imaugs.ScreenshotOverlay(), imaugs.EmojiOverlay(), imaugs.TextOverlay()
```
are not available?

**Comment by WangWenhao0716** [comment]
I know that. They should be 
```
imaugs.OverlayOntoScreenshot(), imaugs.OverlayEmoji(), imaugs.OverlayOntoScreenshot()
```
Please fix the typos in the README file. Thanks for your excellent work,

**Comment by jbitton** [comment]
Thanks for catching this, @WangWenhao0716! Just opened a PR to address this issue in the README
