### ISSUE TITLE
`OverlayStripes()` modifies the input image

### ISSUE THREAD

**Issue by jkim222383** [facebookresearch/AugLy#80]
## 🐛 Bug

`OverlayStripes()` modifies the input image

## To Reproduce

1. Create an instance of `OverlayStripes()` transform 
2. Call transform on an input image
3. Display the input image

```
import os
import augly.image as imaugs
import augly.utils as utils
from IPython.display import display

input_img_path = os.path.join(
    utils.TEST_URI, "image", "inputs", "dfdc_1.jpg"
)
input_img = imaugs.scale(input_img_path, factor=0.2)
display(input_img)

display(imaugs.OverlayStripes()(input_img))

display(input_img)
```

## Expected behavior

I believe `OverlayStripes()` should create a modified copy of the input image without modifying the input image directly. This behaviour would be consistent with other similar methods such as `OverlayOntoScreenshot()`, `OverlayEmoji()`, and `OverlayText()`.

## Environment

 - AugLy Version (e.g., 0.1.2): 0.1.5 
 - OS (e.g., Linux): Linux Ubuntu 20.04
 - How you installed AugLy (`pip install augly`, clone & `pip install -e AugLy`): pip install augly
 - Python version: Python 3.7.9
 - Other relevant packages (Tensorflow, etc):

**Comment by jbitton** [comment]
Hi @jkim222383! Yes, we are aware that `overlay_stripes` modifies the input image -- it's actually on our todo list to address this! I can do it now (ie before addressing your other issue you opened), since it's an easy fix :)

**Comment by jbitton** [comment]
Sorry for the delay in putting this up! Should hopefully get reviewed tomorrow :)
