### ISSUE TITLE
`OSError: unknown freetype error` when using `OverlayText`

### ISSUE THREAD

**Issue by jkim222383** [facebookresearch/AugLy#81]
## To Reproduce

1. `OverlayText` with a combination of specific text [166, 287] and specific font (NotoSansBengaliUI-Regular.ttf") results in error.
2. It appears that even if these two characters (with indices 166 and 287) are separated by any number of other characters, it results in the same error.

```
# imports
import os
import augly.image as imaugs
import augly.utils as utils
from IPython.display import display

# import paths
from augly.utils.base_paths import (
    EMOJI_DIR,
    FONTS_DIR,
    SCREENSHOT_TEMPLATES_DIR,
)

# read sample input_img
input_img_path = os.path.join(
    utils.TEST_URI, "image", "inputs", "dfdc_1.jpg"
)
input_img = imaugs.scale(input_img_path, factor=0.2)

# This results in error
overlay_text = imaugs.OverlayText(
    text = [166, 287],
    font_file = os.path.join(FONTS_DIR, "NotoSansBengaliUI-Regular.ttf"),
)
overlay_text(input_image)

# These do not result in error
overlay_text = imaugs.OverlayText(
    text = [166],
    font_file = os.path.join(FONTS_DIR, "NotoSansBengaliUI-Regular.ttf"),
)
overlay_text(input_image)

# These do not result in error
overlay_text = imaugs.OverlayText(
    text = [287],
    font_file = os.path.join(FONTS_DIR, "NotoSansBengaliUI-Regular.ttf"),
)
overlay_text(input_image)

# These do not result in error
overlay_text = imaugs.OverlayText(
    text = [166, 287]
   # font_file not specified
)
overlay_text(input_image)
```

Stack trace:
```
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-74-a3f6c232cffd> in <module>
      3     font_file = os.path.join(FONTS_DIR, "NotoSansBengaliUI-Regular.ttf"),
      4 )
----> 5 overlay_text(input_image)

~/miniconda3/envs/mds572/lib/python3.7/site-packages/augly/image/transforms.py in __call__(self, image, force, metadata)
     48             return image
     49 
---> 50         return self.apply_transform(image, metadata)
     51 
     52     def apply_transform(

~/miniconda3/envs/mds572/lib/python3.7/site-packages/augly/image/transforms.py in apply_transform(self, image, metadata)
    920             x_pos=self.x_pos,
    921             y_pos=self.y_pos,
--> 922             metadata=metadata,
    923         )
    924 

~/miniconda3/envs/mds572/lib/python3.7/site-packages/augly/image/functional.py in overlay_text(image, output_path, text, font_file, font_size, opacity, color, x_pos, y_pos, metadata)
   1121         text=text_str,
   1122         fill=(color[0], color[1], color[2], round(opacity * 255)),
-> 1123         font=font,
   1124     )
   1125 

~/miniconda3/envs/mds572/lib/python3.7/site-packages/PIL/ImageDraw.py in text(self, xy, text, fill, font, anchor, spacing, align, direction, features, language, stroke_width, stroke_fill, embedded_color, *args, **kwargs)
    461             else:
    462                 # Only draw normal text
--> 463                 draw_text(ink)
    464 
    465     def multiline_text(

~/miniconda3/envs/mds572/lib/python3.7/site-packages/PIL/ImageDraw.py in draw_text(ink, stroke_width, stroke_offset)
    416                     ink=ink,
    417                     *args,
--> 418                     **kwargs,
    419                 )
    420                 coord = coord[0] + offset[0], coord[1] + offset[1]

~/miniconda3/envs/mds572/lib/python3.7/site-packages/PIL/ImageFont.py in getmask2(self, text, mode, fill, direction, features, language, stroke_width, anchor, ink, *args, **kwargs)
    668         """
    669         size, offset = self.font.getsize(
--> 670             text, mode, direction, features, language, anchor
    671         )
    672         size = size[0] + stroke_width * 2, size[1] + stroke_width * 2

OSError: unknown freetype error
```
## Expected behavior

I don't know why this combination of text and font does not work.  I would expect there to be no error, since overlaying the same text using another font file does not result in error. 

## Environment

 - AugLy Version (e.g., 0.1.2): 0.1.5
 - OS (e.g., Linux): Ubuntu 20.04
 - How you installed AugLy (`pip install augly`, clone & `pip install -e AugLy`): `pip install augly`
 - Python version: 3.7.9
 - Other relevant packages (Tensorflow, etc):

## Additional context

Same error message can be reproduced using the following combinations as well:
text `[449, 262]` with font file `NotoSansThaana-Regular.ttf`
text `[295, 481]` with font file `NotoSansBengali-Regular.ttf`

**Comment by jbitton** [comment]
Hi @jkim222383! Thank you so much for reporting this error -- looking into this, and will update you once I have a solution!

**Comment by zpapakipos** [comment]
Hi @jkim222383 thanks for identifying this error! I was able to repro it in a colab notebook with just the lines of PIL code that we call in `OverlayText`, so I think it's an issue with PIL. I submitted an issue on their repo to ask about this: https://github.com/python-pillow/Pillow/issues/5627. It's a super strange error; one weird thing that I found in my notebook was that if I re-ran the cell where the error occurs, the second time the error doesn't occur. Hopefully we'll get some insight from the PIL team!

**Comment by jbitton** [comment]
Hi @jkim222383, someone responded to the issue in PIL saying that if you update your freetype version that your issue should be resolved. (https://github.com/python-pillow/Pillow/issues/5627#issuecomment-885342980)

I'll look this over on Monday and will see if we can automatically include this step in colab. In the meantime, I hope their suggestion unblocks you!

**Comment by radarhere** [comment]
@jkim222383 did upgrading FreeType resolve this for you?

**Comment by zzzzzero** [comment]
> @jkim222383 did upgrading FreeType resolve this for you?

It seems doesn't work for me.
https://colab.research.google.com/drive/1CI4WvOEbJqXdoGkhP6N5PrCqevlxIRil?usp=sharing

**Comment by radarhere** [comment]
That colab isn't public, so I imagine that will hinder people trying to help figure this out.

**Comment by zzzzzero** [comment]
> That colab isn't public, so I imagine that will hinder people trying to help figure this out.
sry，now it‘s ok.
https://colab.research.google.com/drive/1CI4WvOEbJqXdoGkhP6N5PrCqevlxIRil?usp=sharing

**Comment by zzzzzero** [comment]
> You are installing Pillow from a wheel.
> 
> FreeType 2.11.0 was released more recently than the latest Pillow wheel, so the version of FreeType bundled in the wheel would be out of date. This will be fixed with the next release of Pillow on October 15.
> 
> Until then, I suggest changing your Colab to `!pip install -U augly --no-binary Pillow`.
> 
> That said, I'm still struggling to work with Colab to get the install happening correctly. When it works, this code should return 8.3.1 for the Pillow version and 2.11.0 for the FreeType version.


 When I use  `!pip install -U augly --no-binary Pillow`,everything goes well.

> ```python
> from PIL import Image, features;print(Image.__version__, features.version('freetype2'))
> ```
`     8.3.1 2.11.0`

**Comment by jkim222383** [comment]
Yes, I can confirm updating freetype version to 2.11.0 resolved this issue for me.
I'll go ahead and close this issue for now. If I run into a similar issue, I'll follow up in the Pillow issues
