### ISSUE TITLE
can't fine imaugs.apply_ig_filter in the code

### ISSUE THREAD

**Issue by liuzh2016** [facebookresearch/AugLy#82]
Hi, from the readme file, there is a example as follows:
aug_image = imaugs.apply_ig_filter(image_path, filter_name="clarendon")
 but I can't find apply_ig_filter in the source code, could you help me to solve this,thanks

**Comment by jbitton** [comment]
Ahh thank you so much for catching this -- we have the function internally, but have not open sourced it as of yet. We should definitely remove it from the README!
