### ISSUE TITLE
error importing library in colab

### ISSUE THREAD

**Issue by MahdiEsrafili** [facebookresearch/AugLy#86]
## 🐛 Bug

when running the colab notebook located in text augmentation folder, after installation and restarting notebook, the following error after calling library import:

```
NameError                                 Traceback (most recent call last)
<ipython-input-1-3436c02f8201> in <module>()
----> 1 import augly.text as textaugs
      2 
      3 # Define input text
      4 input_text = "Hello, world! How are you today?"
      5 input_text

8 frames
/usr/local/lib/python3.7/dist-packages/nlpaug/model/lang_models/machine_translation_transformers.py in MtTransformers()
     44 
     45     def translate_one_step_batched(
---> 46             self, data, tokenizer: PreTrainedTokenizerBase, model: MarianMTModel
     47     ):
     48         tokenized_texts = tokenizer(data, padding=True, return_tensors='pt')

NameError: name 'PreTrainedTokenizerBase' is not defined
```

## To Reproduce

1. open notebook in https://github.com/facebookresearch/AugLy/tree/main/augly/text
2.run first cell and then restart colab
3. run importing `augly` 

## Expected behavior

importing library without error 

## Environment

 - AugLy Version : latest version
 - OS : Linux
 - How you installed AugLy :
  pip install -U augly
  sudo apt-get install python3-magic
 - Python version: 3.7.3

**Comment by jbitton** [comment]
Hi there, this seems to be a bug in `nlpaug` as opposed to AugLy, but is affecting AugLy. I'll do some digging in `nlpaug` and propose a fix :)

From a quick look, it seems like `nlpaug` has a try/except wrapping the import of PreTrainedTokenizerBase ([file](https://github.com/makcedward/nlpaug/blob/f34e7cd3e6e6b2c714127b9613a27d991b73106e/nlpaug/model/lang_models/machine_translation_transformers.py)), but is then used as a type for a function causing this error to be raised

**Comment by MahdiEsrafili** [comment]
Hi @jbitton , thank you.
