### ISSUE TITLE
New Feature ::::: Add a new function of Resample Audio 

### ISSUE THREAD

**Issue by tanujdhiman** [facebookresearch/AugLy#95]
## 🚀 Feature

Hello everybody, I want to add a new function in `audio augmentations` to resample the audio.

## Motivation

This is a great function and I found most of the guys are not able to resample audio through so by this `Augly` which is specially for augmentations so we can provide this function to users for our best case.

## Pitch

Resampling audio means increase or decrease the sample rate of audio. For example audio has sample rate from `22050` to `44100`.

## Alternatives

* Loading audio file
* Taking target sample rate from user
* Apply augmentation

**Comment by tanujdhiman** [comment]
Hello again !!
I want to know about this feature? Should I start implement this?

**Comment by zpapakipos** [comment]
Hi @tanujdhiman, since no one else has commented on this issue or indicated that they want this function, I don't see any pressing need to implement it now. We appreciate your enthusiasm about AugLy, but please understand that we are just 2 engineers & have limited time, so we only want to invest time into reviewing & landing code that will be directly useful :)

**Comment by tanujdhiman** [comment]
Thanks for replying @zpapakipos !!

I want to more communicate with you. I am a final year Student and looking for a internship role in the area of Machine Learning and Artificial Intelligence. Is it possible to reward me an opportunity on basis on my new ideas, on my work (from June 20, 2021 to December 17, 2021 ), on the basis of my open source and on my resume (if you can say I can share) too. I am very thankful for you for this. I have sent connection request on linkedin too but I think you are a bit busy. So I am writing my message here. Looking forward to hearing from your end.

Thanks
Tanuj

**Comment by jbitton** [comment]
Hi @tanujdhiman, we appreciate your enthusiasm and your contribution to AugLy. I know that searching for internships can be a grueling and frustrating process, but unfortunately we do not have the authority to grant internships. If you're interested in applying for an internship at Meta, feel free to submit an application on https://www.facebookcareers.com/ :)

Closing this issue for now, as we've decided not to add this augmentation at this time :)

**Comment by tanujdhiman** [comment]
Thanks for replying @jbitton !!

Yes. It is. Actually I was saying about giving referral type for a particular role.
Thanks
Tanuj
