### ISSUE TITLE
My GNU Grub laptop is locked to Arch 

### ISSUE THREAD

**Issue by AUGSTEYR** [facebookresearch/AugLy#98]
## To Reproduce

1.
2.
3.

## Environment

 - AugLy Version (e.g., 0.1.2):
 - OS (e.g., Linux):
 - How you installed AugLy (`pip install augly`, clone & `pip install -e AugLy`):
 - Python version:
 - Other relevant packages (Tensorflow, etc):

**Comment by jbitton** [comment]
Since this doesn't seem to be relevant to our library, I'm gonna close this issue. Feel free to reopen and update the description if you need help with AugLy
